default: &default
  host: localhost
  port: 3306 
  user: root 
  pass: root
  database: orm_mysql

dev:
  <<: *default

prod: 
  <<: *default
  user: <%= ENV["MYSQL_USER"] || "root" %>
  pass: <%= ENV["MYSQL_PASS"] || "root" %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>
  port: <%= ENV["MYSQL_PORT"] || "3306" %>
  database: <%= ENV["MYSQL_DATABASE"] || "orm_mysql_prod" %> 